// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AppmodelsReadAppModelsData, AppmodelsReadAppModelsResponse, AppmodelsCreateAppModelData, AppmodelsCreateAppModelResponse, AppmodelsReadAppModelData, AppmodelsReadAppModelResponse, AppmodelsUpdateAppModelData, AppmodelsUpdateAppModelResponse, AppmodelsDeleteAppModelData, AppmodelsDeleteAppModelResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, OntoModelGeneratorUploadModelFileData, OntoModelGeneratorUploadModelFileResponse, OntoModelGeneratorRunApplicationResponse, OntoModelGeneratorStopApplicationResponse, OntoModelGeneratorProcessDataSentFromFrontendResponse, OntoModelGeneratorReadCurrentAppDataFromModelResponse, OntoModelGeneratorReadTheListOfAppModelsResponse, OntoModelGeneratorLoadInnerServerModelData, OntoModelGeneratorLoadInnerServerModelResponse, PrivateCreateUserData, PrivateCreateUserResponse, StreamStreamAiData, StreamStreamAiResponse, TextProcessingGetWordCountData, TextProcessingGetWordCountResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class AppmodelsService {
    /**
     * Read App Models
     * Retrieve app models.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns AppModelsPublic Successful Response
     * @throws ApiError
     */
    public static readAppModels(data: AppmodelsReadAppModelsData = {}): CancelablePromise<AppmodelsReadAppModelsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/appmodels/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create App Model
     * Create new app model.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AppModelPublic Successful Response
     * @throws ApiError
     */
    public static createAppModel(data: AppmodelsCreateAppModelData): CancelablePromise<AppmodelsCreateAppModelResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/appmodels/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read App Model
     * Get app model by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns AppModelPublic Successful Response
     * @throws ApiError
     */
    public static readAppModel(data: AppmodelsReadAppModelData): CancelablePromise<AppmodelsReadAppModelResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/appmodels/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update App Model
     * Update an app model.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns AppModelPublic Successful Response
     * @throws ApiError
     */
    public static updateAppModel(data: AppmodelsUpdateAppModelData): CancelablePromise<AppmodelsUpdateAppModelResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/appmodels/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete App Model
     * Delete an app model.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteAppModel(data: AppmodelsDeleteAppModelData): CancelablePromise<AppmodelsDeleteAppModelResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/appmodels/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class OntoModelGeneratorService {
    /**
     * Upload Model File
     * Uploads a new model file and reads it into the inner application model.
     * @param data The data for the request.
     * @param data.formData
     * @returns unknown Upload new model file
     * @throws ApiError
     */
    public static uploadModelFile(data: OntoModelGeneratorUploadModelFileData): CancelablePromise<OntoModelGeneratorUploadModelFileResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/generator/upload_rdf_file',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Run Application
     * Runs the application by creating an instance of the ProcessEngine.
     * If the application was already run before, it displays a message
     * indicating that the application is running.
     * @returns unknown Run the application
     * @throws ApiError
     */
    public static runApplication(): CancelablePromise<OntoModelGeneratorRunApplicationResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/generator/run_application'
        });
    }
    
    /**
     * Stop Application
     * This function stops the application if it is already running.
     * @returns unknown Shut down the running application
     * @throws ApiError
     */
    public static stopApplication(): CancelablePromise<OntoModelGeneratorStopApplicationResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/generator/stop_application'
        });
    }
    
    /**
     * Process Data Sent From Frontend
     * Receiving the current data form the frontend (e.g. UI page). This method is called
     * before reading the data from the interactive model and then is used the method
     * app_exchange_get are used to complete data exchange between the frontend and the backend.
     * @returns unknown Process the data sent from the frontend
     * @throws ApiError
     */
    public static processDataSentFromFrontend(): CancelablePromise<OntoModelGeneratorProcessDataSentFromFrontendResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/generator/app_exchange_post'
        });
    }
    
    /**
     * Read Current App Data From Model
     * Reading the data from the the interactive model (e.g. UI page) and
     * returns it in the json format to the frontend. This route is called after
     * processing the data sent from the frontend and both methods are used to
     * make data exchange between the frontend and the backend.
     * @returns AppExchangeGetOutput Get current UI page
     * @throws ApiError
     */
    public static readCurrentAppDataFromModel(): CancelablePromise<OntoModelGeneratorReadCurrentAppDataFromModelResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/generator/app_exchange_get'
        });
    }
    
    /**
     * Read The List Of App Models
     * Reads the current list of inner model files in the folder 'app_models' into
     * json format.
     * @returns unknown Get current list of inner UI models on the server
     * @throws ApiError
     */
    public static readTheListOfAppModels(): CancelablePromise<OntoModelGeneratorReadTheListOfAppModelsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/generator/read_inner_server_models'
        });
    }
    
    /**
     * Load Inner Server Model
     * Load the chosen inner UI model from the server.
     *
     * Args:
     * filename (str): The name of the UI model file to be loaded.
     * This file is stored in the 'app_models' folder as RDF file
     * @param data The data for the request.
     * @param data.filename
     * @param data.forceLoad Force reload the model
     * @returns unknown Load the chosen app model on the server
     * @throws ApiError
     */
    public static loadInnerServerModel(data: OntoModelGeneratorLoadInnerServerModelData): CancelablePromise<OntoModelGeneratorLoadInnerServerModelResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/generator/load_inner_uimodel_from_server',
            query: {
                filename: data.filename,
                force_load: data.forceLoad
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class StreamService {
    /**
     * Stream Ai
     * @param data The data for the request.
     * @param data.prompt
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static streamAi(data: StreamStreamAiData): CancelablePromise<StreamStreamAiResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/stream/stream',
            query: {
                prompt: data.prompt
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class TextProcessingService {
    /**
     * Get Word Count
     * Receives a text payload and returns the word count.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns WordCountResponse Successful Response
     * @throws ApiError
     */
    public static getWordCount(data: TextProcessingGetWordCountData): CancelablePromise<TextProcessingGetWordCountResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/processing/text/word-count',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}