// This file is auto-generated by @hey-api/openapi-ts

/**
 * This class represents the data which is sent from the backend
 * to the frontend. If the frontend has to show the form then
 * an object of this class contains JSONForm elements to
 * create that form.
 */
export type AppExchangeGetOutput = {
    message_type: 'layout' | 'notification' | 'information' | 'error';
    layout_type: 'form' | 'message-box' | '';
    message_content: {
        [key: string]: unknown;
    };
    output_knowledge_graph: string;
};

export type message_type = 'layout' | 'notification' | 'information' | 'error';

export type layout_type = 'form' | 'message-box' | '';

export type AppModelCreate = {
    title: string;
    description?: (string | null);
};

export type AppModelPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    knowledge_graph_rdf: string;
};

export type AppModelsPublic = {
    data: Array<AppModelPublic>;
    count: number;
};

export type AppModelUpdate = {
    title?: (string | null);
    description?: (string | null);
    knowledge_graph_rdf: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_onto_model_generator_upload_model_file = {
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type TextProcessRequest = {
    /**
     * The text to be processed.
     */
    text: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WordCountResponse = {
    word_count: number;
    text_length: number;
    message: string;
};

export type AppmodelsReadAppModelsData = {
    limit?: number;
    skip?: number;
};

export type AppmodelsReadAppModelsResponse = (AppModelsPublic);

export type AppmodelsCreateAppModelData = {
    requestBody: AppModelCreate;
};

export type AppmodelsCreateAppModelResponse = (AppModelPublic);

export type AppmodelsReadAppModelData = {
    id: string;
};

export type AppmodelsReadAppModelResponse = (AppModelPublic);

export type AppmodelsUpdateAppModelData = {
    id: string;
    requestBody: AppModelUpdate;
};

export type AppmodelsUpdateAppModelResponse = (AppModelPublic);

export type AppmodelsDeleteAppModelData = {
    id: string;
};

export type AppmodelsDeleteAppModelResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OntoModelGeneratorUploadModelFileData = {
    formData: Body_onto_model_generator_upload_model_file;
};

export type OntoModelGeneratorUploadModelFileResponse = (unknown);

export type OntoModelGeneratorRunApplicationResponse = (unknown);

export type OntoModelGeneratorStopApplicationResponse = (unknown);

export type OntoModelGeneratorProcessDataSentFromFrontendResponse = (unknown);

export type OntoModelGeneratorReadCurrentAppDataFromModelResponse = (AppExchangeGetOutput);

export type OntoModelGeneratorReadTheListOfAppModelsResponse = (unknown);

export type OntoModelGeneratorLoadInnerServerModelData = {
    filename: string;
    /**
     * Force reload the model
     */
    forceLoad?: (boolean | null);
};

export type OntoModelGeneratorLoadInnerServerModelResponse = (unknown);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type StreamStreamAiData = {
    prompt: string;
};

export type StreamStreamAiResponse = (unknown);

export type TextProcessingGetWordCountData = {
    requestBody: TextProcessRequest;
};

export type TextProcessingGetWordCountResponse = (WordCountResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);