plugin: openstack.cloud.openstack

clouds_yaml_path: ~/.config/openstack/clouds.yaml
cloud: mystack

keyed_groups:
  - prefix: env
    key: metadata.env
  - prefix: role
    key: metadata.role

compose:
  ansible_host: public_v4