---
# ansible/terraform_inventory.yml
plugin: community.general.terraform
# Adjust the path to your terraform.tfstate file relative to this inventory file
path: ../infrastructure/terraform/envs/staging/terraform.tfstate